### ISSUE TITLE
compilation error on v1.0.2

### ISSUE THREAD

**Issue by gnuletik** [richardlehane/msoleps#5]
Hi, thanks for this library!

The `v1.0.2` version seems to have an issue:

```sh
mkdir /tmp/test && cd /tmp/test
go mod init example.com/test
go get github.com/richardlehane/msoleps
cat << EOF > main.go
package main

import "github.com/richardlehane/msoleps"

func main() {
	msoleps.New()
}
EOF
go run main.go
rm -rf /tmp/test
cd
```

prints
```
# github.com/richardlehane/msoleps/types
~/go/pkg/mod/github.com/richardlehane/msoleps@v1.0.2/types/vectorArray.go:108:29: syntax error: unexpected newline, expecting := or = or comma
```

It seems that [this fix](https://github.com/richardlehane/msoleps/commit/b5577aceaf9b0617280e8dbc73ce703452b0760b) is not included in the 1.0.2 release.

Can you make a new release from the latest commit?

Thanks :)

**Comment by richardlehane** [comment]
I seem to have mucked up the tagging, sorry! Just pushed a new tag from latest commit, hope this rectifies it.

**Comment by gnuletik** [comment]
Yep, all good, thanks for the fast answer :)
