### ISSUE TITLE
Race in concurrent use of library

### ISSUE THREAD

**Issue by wizardishungry** [richardlehane/msoleps#7]
Hello,

Concurrent usage of this library may cause the race detector to be triggered for concurrent map access. The problem is the global `propertySets`. In the method `func (r *Reader) start(rdr io.Reader) error`, this global is read `dict, ok := propertySets[pss.fmtidA]` and the dictionary is mutated later in the function `dict = addDefaults(dict)`. Concurrent calls to `NewFrom` (etc) will cause the race detector to fail with concurrent map access when this nested map is modified.

I would be happy to write a patch for this (call `maps.Clone` before `addDefaults(dict)`), but I wanted to see if you had another approach & were amenable to a PR. Cheers!

**Comment by wizardishungry** [comment]
I'm sorry! It looks like this was fixed in https://github.com/richardlehane/msoleps/pull/6 :) Mind tagging a new version when you get a minute? :)

**Comment by richardlehane** [comment]
thanks I've just tagged a new release
